# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180523_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='is_tab',
            field=models.BooleanField(default=True, help_text='是否导航', verbose_name='是否导航'),
        ),
    ]
